// Generated by https://quicktype.io

export interface AccountResponse {
  id: string;
  clientId: string;
  balance: string;
  credit: string;
  state: number;
  createdAt: string;
  updatedAt: string;
  deletedAt: null;
  incomes: Come[];
  outcomes: Come[];
}

export interface Come {
  id: string;
  idIncome: string;
  idOutcome: string;
  reason: string;
  amount: string;
  fees: number;
  datetime: string;
}
