// Generated by https://quicktype.io

export interface MovementResponse {
  id?: string;
  idIncome: string;
  idOutcome: string;
  reason: string;
  amount: string;
  fees: number;
  datetime?: string;
}
